<h2><?php echo $this->view->label ?></h2>
<form action="<?php echo $this->view->action ?>" method="post">
    <div class="form-group">
        <label>Nome:</label>
        <input name="nome" required class="form-control" placeholder="Nome" value="<?php echo $this->view->dev->getNome() ?>">
    </div>
    <div class="form-group">
        <label>Nascimento:</label>
        <input name="nascimento" required class="form-control" placeholder="Nascimento" type="date" value="<?php echo $this->view->dev->getNascimento() ?>">
    </div>
    <div class="form-group">
        <label>Nivel:</label>
        <input name="nivel" required class="form-control" placeholder="Nivel" value="<?php echo $this->view->dev->getNivel() ?>">
    </div>


    <div class="form-group">
        <button type="submit" class="<?php echo $this->view->class_btn ?>" ><?php echo $this->view->label ?></button>
        <a class="btn btn-info" href="/dev">voltar</a>
    </div>

</form>