
<div class="row">
    <h1>Lista de desenvolvedores</h1>
    <p>Veja todos os desenvolvedores</p>
</div>
<div class="form-group">
    <a class="btn btn-info" href="/dev/create">Cadastrar Desenvolvedor</a>
    <br><br>
    <nav class="navbar navbar-light bg-light">
        <form class="form-inline" action="/dev/search" method="post">
            <input class="form-control mr-sm-2" name="nome" type="search" placeholder="Nome do desenvolvedor" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procurar</button>
        </form>
    </nav>

</div>
<table class="table table-striped">
    <tr>
        <td>Titulo</td>
        <td>Ação</td>
    </tr>
    <?php foreach ($this->view->devs as $a){ ?>
        <tr>
            <td><a href="/dev/update/<?php echo $a->getId() ?>"><?php echo $a->getNome() ?></td>
            <td><a class="btn btn-danger" href="/dev/delete/<?php echo $a->getId() ?>">&times</a></td>
        </tr>
    <?php } ?>
</table>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php for($i = 1; $i < $this->view->numPaginas + 1; $i++) { ?>
            <li class="page-item"><a class="page-link" href="/dev/index/<?php echo $i ?>"><?php echo $i ?></a></li>
        <?php } ?>
    </ul>
</nav>