<h2><?php echo $this->view->label ?></h2>
<form action="<?php echo $this->view->action ?>" method="post">
    <div class="form-group">
        <label>Titulo:</label>
        <input name="titulo" required class="form-control" placeholder="Titulo" value="<?php echo $this->view->artigo->getTitulo() ?>">
    </div>
    <div class="form-group">
        <label>Texto:</label>
        <textarea name="texto" required class="form-control"><?php echo $this->view->artigo->getTexto() ?></textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="<?php echo $this->view->class_btn ?>" ><?php echo $this->view->label ?></button>
        <a class="btn btn-info" href="/artigo">voltar</a>
    </div>
</form>