<div class="row">
    <h1>Lista de artigos</h1>
    <p>Veja todos os artigos</p>

<div class="form-group">
    <a class="btn btn-info" href="/artigo/create">Cadastrar</a>
    <br><br>
    <nav class="navbar navbar-light bg-light">
        <form class="form-inline" action="/artigo/search" method="post">
            <input class="form-control mr-sm-2" name="titulo" type="search" placeholder="Nome do artigo" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Procurar</button>
        </form>
    </nav>
</div>


<table class="table table-striped">
    <tr>
        <td>Titulo</td>
        <td>Ação</td>
    </tr>
    <?php foreach ($this->view->artigo as $a){ ?>
        <tr>
            <td><a href="/artigo/update/<?php echo $a->getId() ?>"><?php echo $a->getTitulo() ?></td>
            <td><a class="btn btn-danger" href="/artigo/delete/<?php echo $a->getId() ?>">&times</a></td>
        </tr>
    <?php } ?>
</table>
<div class="form-group">

    <a class="btn btn-info" href="/artigo">voltar</a>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php for($i = 1; $i < $this->view->numPaginas + 1; $i++) { ?>
            <li class="page-item"><a class="page-link" href="/artigo/index/<?php echo $i ?>"><?php echo $i ?></a></li>
        <?php } ?>
    </ul>
</nav>