
  <nav class="navbar navbar-expand-lg navbar-light pb-1">
    <div class="container"> <a class="navbar-brand text-primary my-0" href="#">
        <img src="https://unisalesiano.com.br/aracatuba/wp-content/themes/unisalesiano/img/logo.svg" style="width:230px; display:block;">
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar5">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar5">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item my-1">
            <a class="btn navbar-btn ml-md-2 btn-outline-danger" href="#">Comunidade </a>
          </li>
          <li class="nav-item my-1">
            <a class="btn navbar-btn ml-md-2 btn-outline-danger" href="#">Área do Aluno </a>
          </li>
          <li class="nav-item my-1">
            <a class="btn navbar-btn ml-md-2 btn-outline-danger" href="#">Área do Professor </a>
          </li>
          <li class="nav-item my-1"> <a class="nav-link" href="#">Login / Cadastre-se<br></a> </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="">
    <div>
      <div class="">
        <div class="col-md-12 m-0 p-0">
          <div class="carousel slide" data-ride="carousel" id="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active"> <img class="d-block img-fluid w-100" src="https://unisalesiano.com.br/aracatuba/wp-content/uploads/2020/09/capaaparecida.jpg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p> </p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid w-100" src="https://unisalesiano.com.br/aracatuba/wp-content/uploads/2020/10/Vestibular_Geral_Site1.jpg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p> </p>
                </div>
              </div>
              <div class="carousel-item"> <img class="d-block img-fluid w-100" src="https://unisalesiano.com.br/aracatuba/wp-content/uploads/2020/10/Banner-capa-site.jpg">
                <div class="carousel-caption">
                  <h5 class="m-0">Carousel</h5>
                  <p> </p>
                </div>
              </div>
            </div> <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev"> <span class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#carousel" role="button" data-slide="next"> <span class="carousel-control-next-icon"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12 py-2">
          <div class="row">
            <div class="col-md-8">
              <h1 class="">Acesso Rápido<br></h1>
            </div>
            <div class="col-md-4 align-items-end">
              <form class="form-inline m-0 py-2">
                <div class="input-group w-100">
                  <input type="text" class="form-control m-0" id="inlineFormInputGroup" placeholder="Buscar">
                  <div class="input-group-append"><button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button></div>
                </div>
              </form>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 my-1" style=""><a class="btn btn-outline-primary" href="#proj"><i class="fa fa-fw fa-users"></i>&nbsp;O Projeto Comunitário </a></div>
            <div class="col-md-3 my-1" style=""><a class="btn btn-outline-primary" href="#cron"><i class="fa fa-fw fa-th-list"></i>&nbsp;Cronograma </a></div>
            <div class="col-md-3 my-1" style=""><a class="btn btn-outline-primary" href="#"><i class="fa fa-fw fa-handshake-o"></i>&nbsp;Instituições Parceiras </a></div>
            <div class="col-md-3 my-1" style=""><a class="btn btn-outline-primary" href="#faq"><i class="fa fa-fw fa-question-circle-o"></i>&nbsp;Dúvidas Frequentes </a></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-1 bg-danger">
    <div class="container">
      <div class="row">
        <div class="col-md-3 justify-content-center align-items-center flex-grow-0"><a class="btn btn-light w-100 m-1" href="#">Áreas de Atuação</a></div>
        <div class="col-md-3"><a class="btn btn-light w-100 m-1" href="#">Materiais de Apoio</a></div>
        <div class="col-md-3"><a class="btn btn-light w-100 m-1" href="#">Inscrições</a></div>
        <div class="col-md-3"><a class="btn btn-light w-100 m-1" href="#news">Notícias</a></div>
      </div>
    </div>
  </div>
  <div class="py-1 bg-primary text-light mt-3" id="proj">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">O Projeto Comunitário<br></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4 p-3"> <img class="img-fluid d-block" src="https://images.hdqwalls.com/wallpapers/city-blurred-hd.jpg"> </div>
        <div class="col-md-4 p-3"> <img class="d-block img-fluid" src="https://image.freepik.com/free-photo/blurred-city-lights_23-2148139073.jpg"> </div>
        <div class="col-md-4 p-3"> <img class="img-fluid d-block" src="https://slideshare-wordpress-blog-pictures.s3.amazonaws.com/blurredimageblog.jpg"> </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="">O projeto Comunitario visa ajudar pessoas com necessidades em comunidades carentes de recursos ou mão de obra simples, ajudando ao proximo e sem retorno financeiro.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-1 bg-primary text-light mt-3" id="cron">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">Cronograma<br></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-6 p-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title border-bottom border-primary"><b>Período de Inscrições</b></h5>
              <p class="card-text">O periodo de inscrições será realizado entre o dia 23/10/2020 (Sexta-feira) até o dia 12/11/2020 (Quarta-feira). (O cronograma poderá sofrer ajustes de acordo com o planejamento do projeto). </p>
              <a href="#" class="card-link text-primary">Ler mais</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 p-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title border-bottom border-primary"><b>Início das Atividades</b><br></h5>
              <p class="card-text"> O inicio das atividades estão planejadas para começar dia 15/03/2021(Segunda-feira) e sendo finalizadas no dia 04/04/2021. (O cronograma poderá sofrer ajustes de acordo com o andamento do projeto). </p>
              <a href="#" class="card-link text-primary">Ler mais</a>
              <a href="#" class="card-link text-danger">Calendário Acadêmico<br></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-1 bg-primary text-light mt-3" id="faq">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">Dúvidas Frequentes<br></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center py-2">
    <div class="container">
      <div class="row">
        <div class="mx-auto col-md-10"> <i class="d-block fa fa-4x mb-3 fa-question-circle-o text-primary"></i>
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-6 py-1">
                  <li class="border-0 list-group-item d-flex justify-content-between align-items-center list-group-item-info list-group-item-action"> O QUE É UM PROJETO COMUNITÁRIO? <i class="fa fa-list text-muted fa-angle-down"></i></li>
                </div>
                <div class="col-md-6 py-1">
                  <li class="border-0 list-group-item d-flex justify-content-between align-items-center list-group-item-info"> COMO FAÇO PARA ME INSCREVER <i class="fa fa-list text-muted fa-angle-down"></i></li>
                  <ul class="list-group">
                  </ul>
                </div>
                <div class="col-md-6 py-1">
                  <li class="border-0 list-group-item d-flex justify-content-between align-items-center list-group-item-info"> COMO FUNCIONA UM PROJETO COMUNITÁRIO? <i class="fa fa-list text-muted fa-angle-down"></i></li>
                </div>
                <div class="col-md-6 py-1">
                  <li class="border-0 list-group-item d-flex justify-content-between align-items-center list-group-item-info"> QUANTAS HORAS? <i class="fa fa-list text-muted fa-angle-down"></i></li>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12 text-center"><a class="btn btn-block btn-outline-light text-dark" href="#"><i class="fa fa-fw fa-plus-circle"></i> Carregar Mais </a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 text-white bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="text-light mb-4" id="news">Notícias<br></h1>
        </div>
      </div>
      <div class="row text-dark">
        <div class="col-lg-4 p-3">
          <div class="card text-center">
            <div class="card-body p-4">
              <h3>Notícia 1</h3>
              <p class="my-3 lead"><img src="2test.jpg"> &nbsp;</p> <a class="btn btn-link" href="https://unisalesiano.com.br/aracatuba/docente-de-engenharia-do-unisalesiano-vence-campeonato-entre-hackers/" target="_blank">Ler mais<br></a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 p-3">
          <div class="card text-center">
            <div class="card-body p-4">
              <h3>Notícia 2</h3>
              <p class="my-3 lead"><img src="1test.jpg"></p> <a class="btn btn-link" href="https://unisalesiano.com.br/aracatuba/unisalesiano-promovera-a-6a-edicao-do-outubro-rosa-pet-por-meio-de-agendamento/" target="_blank">Ler mais</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 p-3">
          <div class="card text-center">
            <div class="card-body p-4">
              <h3>Notícia 3<br></h3>
              <p class="my-3 lead">&nbsp;<img src="3test.jpg"></p> <a class="btn btn-link" href="https://unisalesiano.com.br/aracatuba/1o-congresso-medico-interligas-do-unisalesiano-tera-como-tema-central-a-saude-da-mulher/" target="_blank">Ler mais</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-light py-3" style="	background-image: url(https://unisalesiano.com.br/aracatuba/wp-content/themes/unisalesiano/img/bg-footer.jpg);	background-position: top left;	background-size: 100%;	background-repeat: repeat;">
    <div class="container">
      <div class="row">
        <div class="col-md-12"><img class="img-fluid d-block" src="https://unisalesiano.com.br/aracatuba/wp-content/themes/unisalesiano/img/logo-footer.png"></div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <p class="m-0">Rod. Teotônio Vilela, 3821, Jd. Alvorada</p>
          <p class="m-0">16016-500 - Araçatuba-SP</p>
          <p class="m-0">Tel: (18) 3636-5252</p>
          <p class="m-0">unisalesiano@unisalesiano.com.br</p>
        </div>
        <div class="col-4 col-md-1 align-self-center"> <a href="#">
            <i class="fa fa-fw fa-facebook fa-2x text-light"></i>
          </a> </div>
        <div class="col-4 col-md-1 align-self-center"> <a href="#">
            <i class="fa fa-fw fa-2x text-light fa-instagram"></i>
          </a> </div>
        <div class="col-4 col-md-1 align-self-center"> <a href="#">
            <i class="fa fa-fw fa-2x text-light fa-youtube-play"></i>
          </a> </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3 text-center">
          <p class="m-0">© Copyright 2020 UniSalesiano - Todos os Direitos Reservados.</p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous" style=""></script>
