
<div class="row">
    <h1>Index</h1>
    <h2>Menu</h2>
    <h3>TesteOPAAAA</h3>

    <ul>
        <li><a href="/artigo/create">Cadastrar artigo</a></li>
        <li><a href="/dev/create">Cadastrar desenvolvedor</a></li>
    </ul>
    <br>
    <hr>
    <br>
    <table class="table table-striped">
        <tr>
            <td><b>Titulos cadastrados</b></td>

        </tr>
        <?php foreach ($this->view->artigos as $a){ ?>
            <tr>
                <td><a href="/artigo/update/<?php echo $a->getId() ?>"><?php echo $a->getTitulo() ?></td>
            </tr>
        <?php } ?>

    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <?php for($i = 1; $i < $this->view->numPaginas + 1; $i++) { ?>
                <li class="page-item"><a class="page-link" href="/home/index/<?php echo $i ?>"><?php echo $i ?></a></li>
            <?php } ?>
        </ul>
    </nav>
